# Generated by Django 4.2.7 on 2023-11-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_articles_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.CharField(choices=[('3D', '3D-Дизайн'), ('2D', '2D-Дизайн'), ('sketch', 'Эскиз'), ('Other', 'Прочее')], max_length=50, verbose_name='Категория'),
        ),
    ]
